---
galaxy_info:
  author: Simon Baerlocher (https://sbaerlocher.ch)
  description: Downloads a file or creates one from a structure.
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Windows
      versions:
        - all

  galaxy_tags:
    - windows
    - files

dependencies: []
