---
# tasks file for sbaerlocher.remote-desktop

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.TerminalServer::TS_DISABLE_CONNECTIONS
- name: Allow users to connect remotely by using Remote Desktop Services
  win_regedit:
    path: '{{ item }}'
    name: fDenyTSConnections
    data: 00000000
    type: dword
    state: "{{ 'present' if remote_desktop_enabled else 'absent' }}"
  register: register_remote_desktop_enabled
  with_items:
    - "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\"
    - "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services"
  tags:
    - configuration

- name: Firewall Enable or Disable rule for Remote Desktop Services
  win_shell: >
    "{{ 'Enable-NetFirewallRule' if rd_enable else 'Disable-NetFirewallRule' }}
    -DisplayGroup 'Remotedesktop'"
  vars:
    rd_enable: '{{ remote_desktop_enabled }}'
  tags:
    - configuration

- name: Set then Remote Desktop Port
  win_regedit:
    path: "{{ path }}\\Control\\Terminal Server\\WinStations\\RDP-Tcp"
    name: PortNumber
    data: '{{ remote_desktop_port }}'
    type: dword
  vars:
    path: "HKLM:\\SYSTEM\\CurrentControlSet"
  tags:
    - configuration

- name: Firewall rule to allow RDP on TCP port 3389
  win_firewall_rule:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    localport: '{{ remote_desktop_port }}'
    action: allow
    direction: in
    protocol: '{{ item.protocol }}'
    profiles: domain,private,public
    state: present
    enabled: "{{ 'true' if remote_desktop_enabled else 'false' }}"
    service: termservice
    program: C:\Windows\system32\svchost.exe
  with_items:
    - name: Remotedesktop - Benutzermodus (TCP eingehend)
      description: >
        Eingehende Regel f체r den Remotedesktopdienst,
         die RDP-Datenverkehr zul채sst. [TCP 3389]
      protocol: tcp
    - name: Remotedesktop - Benutzermodus (UDP eingehend)
      description: >
        Eingehende Regel f체r den Remotedesktopdienst,
         die RDP-Datenverkehr zul채sst. [UDP 3389]
      protocol: udp
  tags:
    - configuration

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.TerminalServer::TS_SECURITY_LAYER_POLICY
- name: Require use of specific security layer for remote (RDP) connections
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
    name: SecurityLayer
    data: '{{ remote_desktop_securitylayer }}'
    type: dword
    state: "{{ 'present' if remote_desktop_enabled else 'absent' }}"
  tags:
    - configuration

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.TerminalServer::TS_ENCRYPTION_POLICY
- name: Set client connection encryption level
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
    name: MinEncryptionLevel
    data: '{{ remote_desktop_minencryptionLevel }}'
    type: dword
    state: "{{ 'present' if remote_desktop_enabled else 'absent' }}"
  tags:
    - configuration

- name: Add User or Group to Login group for Remote Desktop
  win_group_membership:
    name: '{{ remote_desktop_group }}'
    members: '{{ remote_desktop_members }}'
    state: present
  tags:
    - configuration

# https://www.winfaq.de/faq_html/Content/tip1000/onlinefaq.php?h=tip1368.htm
- name: Disable Shutdown Butten from Windows Start
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer
    name: NoClose
    data: '1'
    type: dword
    state: "{{ 'present' if rd_enable and rd_shutdown_disable else 'absent' }}"
  vars:
    rd_enable: '{{ remote_desktop_enabled }}'
    rd_shutdown_disable: '{{ remote_desktop_shutdown_disable }}'
  tags:
    - configuration

# https://www.howtogeek.com/246728/how-to-remove-the-shutdown-button-from-the-windows-login-screen/
- name: Disable Shutdown Butten from Windows login screen
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: shutdownwithoutlogon
    data: "{{ '0' if rd_enable and rd_shutdown_disable else '1' }}"
    type: dword
  vars:
    rd_enable: '{{ remote_desktop_enabled }}'
    rd_shutdown_disable: '{{ remote_desktop_shutdown_disable }}'
  tags:
    - configuration
