---
galaxy_info:
  author: Simon Baerlocher (https://sbaerlocher.ch)
  description: Creates various directory structures on the target system.
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Windows
      versions:
        - all

  galaxy_tags:
    - windows
    - directories

dependencies: []
