---
galaxy_info:
  author: Simon Baerlocher (https://sbaerlocher.ch)
  description: Disables or enables Windows defender on the Windows system.
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Windows
      versions:
        - all

  galaxy_tags:
    - windows
    - defender

dependencies: []
