---
galaxy_info:
  author: Simon Baerlocher (https://sbaerlocher.ch)
  description: Create scheduled tasks.
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Windows
      versions:
        - all

  galaxy_tags:
    - windows
    - scheduled_tasks

dependencies: []
