---
# tasks file for files

- name: "Create {{ file.path }}\\{{ file.name }}.{{ file.extension }}"
  win_get_url:
    url: '{{ file.url }}'
    dest: '{{ file.path }}\\{{ file.name }}.{{ file.extension }}'
  when: file.state | default("present") == "present"

- name: "Absent {{ file.path }}\\{{ file.name }}.{{ file.extension }}"
  win_file:
    path: "{{ file.path }}\\{{ file.name }}.{{ file.extension }}"
    state: absent
  when:
    - ("state" in file.keys())
    - file.state == "absent"
